### ISSUE TITLE
Migration to version 8

### ISSUE THREAD

**Issue by max3903** [OCA/vertical-construction#2]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-8
# Modules to migrate
- [ ] account_invoice_insulation
- [ ] construction_insulation
- [ ] procurement_insulation
- [ ] product_insulation
- [ ] sale_insulation
- [ ] stock_picking_delivery_insulation
- [ ] stock_picking_delivery_users

**Comment by mathi123** [comment]
Is a reason why there are so many modules for insulation? 
Except for product_insulation, they can't be used separately. I suggest creating 2 modules:
    - product_insulation: to add the field on product form.
    - sale_insulation: all the rest of the reports, pickings, ...

BTW: Is it any use to port this modules? In the reports I see references to a company that does not exist anymore?

**Comment by max3903** [comment]
@mathi123 These modules were developed during one of our first projects and are not used anymore (company is now closed).

No need to port those modules, unless you plan to use them.

On the other hand, it does not prevent you from going through pull requests. Can you please remove your modules from 8.0 branch and follow the review and testing process ?

**Comment by mathi123** [comment]
@max3903 I have created one here: https://github.com/OCA/vertical-construction/pull/3

**Comment by mathi123** [comment]
@max3903  PR where created now, sorry for that.
If anyone has any use the insulation or delivery_users modules, I would be happy to port them as an exercise.

**Comment by jacksolutions** [comment]
any use case for those modules? i am not getting how it will be useful? is it useful for any construction company?

**Comment by jacksolutions** [comment]
@mathi123 can you please port them as an excercise, may be me or any one else can use it?
