### ISSUE TITLE
Migration to version 9.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/vertical-construction#22]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0
# Modules to migrate
- [ ] procurement_insulation
- [ ] base_construction_architect
- [ ] crm_construction_site
- [ ] stock_picking_delivery_users
- [ ] project_construction_architect
- [ ] project_construction_site
- [ ] construction_insulation
- [ ] account_invoice_insulation
- [ ] crm_construction_architect
- [ ] sale_insulation
- [ ] stock_picking_delivery_insulation
- [ ] crm_construction_calculator
