### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/vertical-construction#24]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
# Modules to migrate
- [ ] account_invoice_insulation
- [ ] base_construction_architect
- [ ] construction_insulation
- [ ] crm_construction_architect
- [ ] crm_construction_calculator
- [ ] crm_construction_site
- [ ] procurement_insulation
- [ ] project_construction_architect
- [ ] project_construction_site
- [ ] sale_insulation
- [ ] stock_picking_delivery_insulation
- [ ] stock_picking_delivery_users

**Comment by b5baxter** [comment]
would like to migrate crm_construction_architect to 10.0

**Comment by pedrobaeza** [comment]
OK, go ahead!
