### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/vertical-construction#25]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [ ] account_invoice_insulation
- [ ] base_construction_architect
- [ ] construction_insulation
- [ ] crm_construction_architect
- [ ] crm_construction_calculator
- [ ] crm_construction_site
- [ ] procurement_insulation
- [ ] project_construction_architect
- [ ] project_construction_site
- [ ] sale_insulation
- [ ] stock_picking_delivery_insulation
- [ ] stock_picking_delivery_users
